python3 main.py -e FAST -a Autobahn -g 0 -l True
python3 main.py -e SURF -a Autobahn -g 0 -l True
python3 main.py -e ORB -a Autobahn -g 0 -l True
python3 main.py -e SHI-TOMASI -a Autobahn -g 0 -l True
python3 main.py -e REGULAR_GRID -a Autobahn -g 0 -l True
python3 main.py -e FAST -a Autobahn -g 1 -l True
python3 main.py -e SURF -a Autobahn -g 1 -l True
python3 main.py -e ORB -a Autobahn -g 1 -l True
python3 main.py -e SHI-TOMASI -a Autobahn -g 1 -l True
python3 main.py -e REGULAR_GRID -a Autobahn -g 1 -l True
python3 main.py -e FAST -a KITTI -g 0 -l True
python3 main.py -e SURF -a KITTI -g 0 -l True
python3 main.py -e ORB -a KITTI -g 0 -l True
python3 main.py -e SHI-TOMASI -a KITTI -g 0 -l True
python3 main.py -e REGULAR_GRID -a KITTI -g 0 -l True
python3 main.py -e FAST -a KITTI -g 1 -l True
python3 main.py -e SURF -a KITTI -g 1 -l True
python3 main.py -e ORB -a KITTI -g 1 -l True
python3 main.py -e SHI-TOMASI -a KITTI -g 1 -l True
python3 main.py -e REGULAR_GRID -a KITTI -g 1 -l True
python3 main.py -e FAST -a Malaga -g 0 -l True
python3 main.py -e SURF -a Malaga -g 0 -l True
python3 main.py -e ORB -a Malaga -g 0 -l True
python3 main.py -e SHI-TOMASI -a Malaga -g 0 -l True
python3 main.py -e REGULAR_GRID -a Malaga -g 0 -l True
python3 main.py -e FAST -a Malaga -g 1 -l True
python3 main.py -e SURF -a Malaga -g 1 -l True
python3 main.py -e ORB -a Malaga -g 1 -l True
python3 main.py -e SHI-TOMASI -a Malaga -g 1 -l True
python3 main.py -e REGULAR_GRID -a Malaga -g 1 -l True
